# Generated by Django 4.2.4 on 2023-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.TextField(max_length=300)),
                ('lecture_img', models.ImageField(upload_to='')),
                ('teacher', models.CharField(max_length=300)),
                ('lecture_url', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('platform', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
            ],
        ),
    ]
